# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.add_notification_notification_data import AddNotificationNotificationData  # noqa: F401,E501
from swagger_server import util


class Body1(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, notification_body: str=None, notification_id: int=None, notification_data: AddNotificationNotificationData=None, notification_icon: str=None, notification_title: str=None, notification_type: str=None, read_time: int=None):  # noqa: E501
        """Body1 - a model defined in Swagger

        :param notification_body: The notification_body of this Body1.  # noqa: E501
        :type notification_body: str
        :param notification_id: The notification_id of this Body1.  # noqa: E501
        :type notification_id: int
        :param notification_data: The notification_data of this Body1.  # noqa: E501
        :type notification_data: AddNotificationNotificationData
        :param notification_icon: The notification_icon of this Body1.  # noqa: E501
        :type notification_icon: str
        :param notification_title: The notification_title of this Body1.  # noqa: E501
        :type notification_title: str
        :param notification_type: The notification_type of this Body1.  # noqa: E501
        :type notification_type: str
        :param read_time: The read_time of this Body1.  # noqa: E501
        :type read_time: int
        """
        self.swagger_types = {
            'notification_body': str,
            'notification_id': int,
            'notification_data': AddNotificationNotificationData,
            'notification_icon': str,
            'notification_title': str,
            'notification_type': str,
            'read_time': int
        }

        self.attribute_map = {
            'notification_body': 'Notification_Body',
            'notification_id': 'NotificationID',
            'notification_data': 'Notification_Data',
            'notification_icon': 'Notification_Icon',
            'notification_title': 'Notification_Title',
            'notification_type': 'Notification_Type',
            'read_time': 'Read_Time'
        }
        self._notification_body = notification_body
        self._notification_id = notification_id
        self._notification_data = notification_data
        self._notification_icon = notification_icon
        self._notification_title = notification_title
        self._notification_type = notification_type
        self._read_time = read_time

    @classmethod
    def from_dict(cls, dikt) -> 'Body1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_1 of this Body1.  # noqa: E501
        :rtype: Body1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notification_body(self) -> str:
        """Gets the notification_body of this Body1.

        Body of the Notification  # noqa: E501

        :return: The notification_body of this Body1.
        :rtype: str
        """
        return self._notification_body

    @notification_body.setter
    def notification_body(self, notification_body: str):
        """Sets the notification_body of this Body1.

        Body of the Notification  # noqa: E501

        :param notification_body: The notification_body of this Body1.
        :type notification_body: str
        """

        self._notification_body = notification_body

    @property
    def notification_id(self) -> int:
        """Gets the notification_id of this Body1.

        Unique ID of the notification  # noqa: E501

        :return: The notification_id of this Body1.
        :rtype: int
        """
        return self._notification_id

    @notification_id.setter
    def notification_id(self, notification_id: int):
        """Sets the notification_id of this Body1.

        Unique ID of the notification  # noqa: E501

        :param notification_id: The notification_id of this Body1.
        :type notification_id: int
        """
        if notification_id is None:
            raise ValueError("Invalid value for `notification_id`, must not be `None`")  # noqa: E501

        self._notification_id = notification_id

    @property
    def notification_data(self) -> AddNotificationNotificationData:
        """Gets the notification_data of this Body1.


        :return: The notification_data of this Body1.
        :rtype: AddNotificationNotificationData
        """
        return self._notification_data

    @notification_data.setter
    def notification_data(self, notification_data: AddNotificationNotificationData):
        """Sets the notification_data of this Body1.


        :param notification_data: The notification_data of this Body1.
        :type notification_data: AddNotificationNotificationData
        """
        if notification_data is None:
            raise ValueError("Invalid value for `notification_data`, must not be `None`")  # noqa: E501

        self._notification_data = notification_data

    @property
    def notification_icon(self) -> str:
        """Gets the notification_icon of this Body1.

        Icon of the notification being sent  # noqa: E501

        :return: The notification_icon of this Body1.
        :rtype: str
        """
        return self._notification_icon

    @notification_icon.setter
    def notification_icon(self, notification_icon: str):
        """Sets the notification_icon of this Body1.

        Icon of the notification being sent  # noqa: E501

        :param notification_icon: The notification_icon of this Body1.
        :type notification_icon: str
        """
        if notification_icon is None:
            raise ValueError("Invalid value for `notification_icon`, must not be `None`")  # noqa: E501

        self._notification_icon = notification_icon

    @property
    def notification_title(self) -> str:
        """Gets the notification_title of this Body1.

        Title of the Notification  # noqa: E501

        :return: The notification_title of this Body1.
        :rtype: str
        """
        return self._notification_title

    @notification_title.setter
    def notification_title(self, notification_title: str):
        """Sets the notification_title of this Body1.

        Title of the Notification  # noqa: E501

        :param notification_title: The notification_title of this Body1.
        :type notification_title: str
        """
        if notification_title is None:
            raise ValueError("Invalid value for `notification_title`, must not be `None`")  # noqa: E501

        self._notification_title = notification_title

    @property
    def notification_type(self) -> str:
        """Gets the notification_type of this Body1.

        Different kinds of Notifications  # noqa: E501

        :return: The notification_type of this Body1.
        :rtype: str
        """
        return self._notification_type

    @notification_type.setter
    def notification_type(self, notification_type: str):
        """Sets the notification_type of this Body1.

        Different kinds of Notifications  # noqa: E501

        :param notification_type: The notification_type of this Body1.
        :type notification_type: str
        """
        if notification_type is None:
            raise ValueError("Invalid value for `notification_type`, must not be `None`")  # noqa: E501

        self._notification_type = notification_type

    @property
    def read_time(self) -> int:
        """Gets the read_time of this Body1.

        The time at which the Notification is read  # noqa: E501

        :return: The read_time of this Body1.
        :rtype: int
        """
        return self._read_time

    @read_time.setter
    def read_time(self, read_time: int):
        """Sets the read_time of this Body1.

        The time at which the Notification is read  # noqa: E501

        :param read_time: The read_time of this Body1.
        :type read_time: int
        """
        if read_time is None:
            raise ValueError("Invalid value for `read_time`, must not be `None`")  # noqa: E501

        self._read_time = read_time
