# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, event_id: str=None):  # noqa: E501
        """Body - a model defined in Swagger

        :param event_id: The event_id of this Body.  # noqa: E501
        :type event_id: str
        """
        self.swagger_types = {
            'event_id': str
        }

        self.attribute_map = {
            'event_id': 'EventID'
        }
        self._event_id = event_id

    @classmethod
    def from_dict(cls, dikt) -> 'Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def event_id(self) -> str:
        """Gets the event_id of this Body.

        ID of a particular Event  # noqa: E501

        :return: The event_id of this Body.
        :rtype: str
        """
        return self._event_id

    @event_id.setter
    def event_id(self, event_id: str):
        """Sets the event_id of this Body.

        ID of a particular Event  # noqa: E501

        :param event_id: The event_id of this Body.
        :type event_id: str
        """
        if event_id is None:
            raise ValueError("Invalid value for `event_id`, must not be `None`")  # noqa: E501

        self._event_id = event_id
