# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response200_event import InlineResponse200Event  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, event: InlineResponse200Event=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param event: The event of this InlineResponse200.  # noqa: E501
        :type event: InlineResponse200Event
        """
        self.swagger_types = {
            'event': InlineResponse200Event
        }

        self.attribute_map = {
            'event': 'Event'
        }
        self._event = event

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def event(self) -> InlineResponse200Event:
        """Gets the event of this InlineResponse200.


        :return: The event of this InlineResponse200.
        :rtype: InlineResponse200Event
        """
        return self._event

    @event.setter
    def event(self, event: InlineResponse200Event):
        """Sets the event of this InlineResponse200.


        :param event: The event of this InlineResponse200.
        :type event: InlineResponse200Event
        """

        self._event = event
