# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200Event(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: int=None, notifications: object=None, last_event_id: float=None):  # noqa: E501
        """InlineResponse200Event - a model defined in Swagger

        :param code: The code of this InlineResponse200Event.  # noqa: E501
        :type code: int
        :param notifications: The notifications of this InlineResponse200Event.  # noqa: E501
        :type notifications: object
        :param last_event_id: The last_event_id of this InlineResponse200Event.  # noqa: E501
        :type last_event_id: float
        """
        self.swagger_types = {
            'code': int,
            'notifications': object,
            'last_event_id': float
        }

        self.attribute_map = {
            'code': 'Code',
            'notifications': 'Notifications',
            'last_event_id': 'Last_Event_ID'
        }
        self._code = code
        self._notifications = notifications
        self._last_event_id = last_event_id

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200Event':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_Event of this InlineResponse200Event.  # noqa: E501
        :rtype: InlineResponse200Event
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this InlineResponse200Event.

        Message Code  # noqa: E501

        :return: The code of this InlineResponse200Event.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this InlineResponse200Event.

        Message Code  # noqa: E501

        :param code: The code of this InlineResponse200Event.
        :type code: int
        """

        self._code = code

    @property
    def notifications(self) -> object:
        """Gets the notifications of this InlineResponse200Event.

        Success or Failure Message  # noqa: E501

        :return: The notifications of this InlineResponse200Event.
        :rtype: object
        """
        return self._notifications

    @notifications.setter
    def notifications(self, notifications: object):
        """Sets the notifications of this InlineResponse200Event.

        Success or Failure Message  # noqa: E501

        :param notifications: The notifications of this InlineResponse200Event.
        :type notifications: object
        """

        self._notifications = notifications

    @property
    def last_event_id(self) -> float:
        """Gets the last_event_id of this InlineResponse200Event.

        The ID of the Last Event that was sent  # noqa: E501

        :return: The last_event_id of this InlineResponse200Event.
        :rtype: float
        """
        return self._last_event_id

    @last_event_id.setter
    def last_event_id(self, last_event_id: float):
        """Sets the last_event_id of this InlineResponse200Event.

        The ID of the Last Event that was sent  # noqa: E501

        :param last_event_id: The last_event_id of this InlineResponse200Event.
        :type last_event_id: float
        """

        self._last_event_id = last_event_id
