# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200Events(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, notifications: object=None):  # noqa: E501
        """InlineResponse200Events - a model defined in Swagger

        :param notifications: The notifications of this InlineResponse200Events.  # noqa: E501
        :type notifications: object
        """
        self.swagger_types = {
            'notifications': object
        }

        self.attribute_map = {
            'notifications': 'Notifications'
        }
        self._notifications = notifications

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200Events':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_events of this InlineResponse200Events.  # noqa: E501
        :rtype: InlineResponse200Events
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notifications(self) -> object:
        """Gets the notifications of this InlineResponse200Events.

        Success or Failure Message  # noqa: E501

        :return: The notifications of this InlineResponse200Events.
        :rtype: object
        """
        return self._notifications

    @notifications.setter
    def notifications(self, notifications: object):
        """Sets the notifications of this InlineResponse200Events.

        Success or Failure Message  # noqa: E501

        :param notifications: The notifications of this InlineResponse200Events.
        :type notifications: object
        """

        self._notifications = notifications
