# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: int=None, message: object=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param code: The code of this InlineResponse200.  # noqa: E501
        :type code: int
        :param message: The message of this InlineResponse200.  # noqa: E501
        :type message: object
        """
        self.swagger_types = {
            'code': int,
            'message': object
        }

        self.attribute_map = {
            'code': 'Code',
            'message': 'Message'
        }
        self._code = code
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this InlineResponse200.

        Message Code  # noqa: E501

        :return: The code of this InlineResponse200.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this InlineResponse200.

        Message Code  # noqa: E501

        :param code: The code of this InlineResponse200.
        :type code: int
        """

        self._code = code

    @property
    def message(self) -> object:
        """Gets the message of this InlineResponse200.

        Success or Failure Message  # noqa: E501

        :return: The message of this InlineResponse200.
        :rtype: object
        """
        return self._message

    @message.setter
    def message(self, message: object):
        """Sets the message of this InlineResponse200.

        Success or Failure Message  # noqa: E501

        :param message: The message of this InlineResponse200.
        :type message: object
        """

        self._message = message
