# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, result: str=None, last_event_id: float=None, queue_id: str=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param result: The result of this InlineResponse2001.  # noqa: E501
        :type result: str
        :param last_event_id: The last_event_id of this InlineResponse2001.  # noqa: E501
        :type last_event_id: float
        :param queue_id: The queue_id of this InlineResponse2001.  # noqa: E501
        :type queue_id: str
        """
        self.swagger_types = {
            'result': str,
            'last_event_id': float,
            'queue_id': str
        }

        self.attribute_map = {
            'result': 'result',
            'last_event_id': 'last_event_id',
            'queue_id': 'queue_id'
        }
        self._result = result
        self._last_event_id = last_event_id
        self._queue_id = queue_id

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> str:
        """Gets the result of this InlineResponse2001.

        Success or Failure Message  # noqa: E501

        :return: The result of this InlineResponse2001.
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result: str):
        """Sets the result of this InlineResponse2001.

        Success or Failure Message  # noqa: E501

        :param result: The result of this InlineResponse2001.
        :type result: str
        """

        self._result = result

    @property
    def last_event_id(self) -> float:
        """Gets the last_event_id of this InlineResponse2001.

        Unique ID of a particular Event being accessed  # noqa: E501

        :return: The last_event_id of this InlineResponse2001.
        :rtype: float
        """
        return self._last_event_id

    @last_event_id.setter
    def last_event_id(self, last_event_id: float):
        """Sets the last_event_id of this InlineResponse2001.

        Unique ID of a particular Event being accessed  # noqa: E501

        :param last_event_id: The last_event_id of this InlineResponse2001.
        :type last_event_id: float
        """

        self._last_event_id = last_event_id

    @property
    def queue_id(self) -> str:
        """Gets the queue_id of this InlineResponse2001.

        Unique ID of queue inline of the Event being accessed.  # noqa: E501

        :return: The queue_id of this InlineResponse2001.
        :rtype: str
        """
        return self._queue_id

    @queue_id.setter
    def queue_id(self, queue_id: str):
        """Sets the queue_id of this InlineResponse2001.

        Unique ID of queue inline of the Event being accessed.  # noqa: E501

        :param queue_id: The queue_id of this InlineResponse2001.
        :type queue_id: str
        """

        self._queue_id = queue_id
